fix: add forward declarations for FFI functions in Android JNI
Fixed compilation error: use of undeclared identifier 'lz_logger_ffi_set_handle'

Problem:
- lz_logger_ffi_set_handle() called before declaration
- lz_logger_ffi() also needs forward declaration
- C++ requires function declaration before use

Solution:
- Added forward declarations before extern "C" block:
  extern "C" void lz_logger_ffi_set_handle(lz_logger_handle_t handle);
  extern "C" void lz_logger_ffi(int level, const char* tag, ...);

This allows nativeSetFfiHandle() to call lz_logger_ffi_set_handle()
even though the actual implementation is later in the file